language: android
android:
 components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-28

  # Additional components
  - extra-android-support
  - extra-android-m2repository

licenses:
  - 'android-sdk-license-.+'

script:
  - ./gradlew build connectedCheck

before_install:
  - yes | sdkmanager "platforms;android-27"

branches:
 only:
   - master

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/reports/lint-results.xml"
